os: linux
dist: bionic
language: shell

services:
  - docker

env:
  - version: v3.0.0
  - version: v3.1.0
  - version: v3.2.0
  - version: v3.3.0
  - version: v3.3.1
  - version: v4.0.0
  - version: v4.0.1
  - version: v4.0.2

before_install: 
  - docker build --build-arg citydb_version=${version} -t tumgis/3dcitydb-postgis:${version} ./${version}
  - docker build --build-arg citydb_version=${version} -t tumgis/3dcitydb-postgis:${version}-alpine ./${version}/alpine

before_script:
  - sleep 5
  - docker run --name ${version} -dit -e POSTGRES_PASSWORD=password -e "SRID=31468" -e "SRSNAME=EPSG:31468" tumgis/3dcitydb-postgis:${version}
  - docker run --name ${version}-alpine -e POSTGRES_PASSWORD=password -dit -e "SRID=31468" -e "SRSNAME=EPSG:31468" tumgis/3dcitydb-postgis:${version}-alpine
  # - docker logs ${version}
  # - docker logs ${version}-alpine
  - docker images
  - docker ps -a

script:
  - sleep 30
  - docker logs ${version} | grep -Pzl '(?s)Setting up 3DCityDB ...done!.*database system is ready to accept connections'
  - docker logs ${version}-alpine | grep -Pzl '(?s)Setting up 3DCityDB ...done!.*database system is ready to accept connections'
#  - docker logs ${version}
#  - docker logs ${version}-alpine
  
notifications:
    slack: tum-gis:Z32lHXJDXaycOn4643NHSXaT
    on_success: change
    on_failure: always
