language: bash
sudo: required

services:
  - docker

env:
  - version: v3.0.0
  - version: v3.1.0
  - version: v3.2.0
  - version: v3.3.0
  - version: v3.3.1
  - version: v4.0.0

before_install: 
  - docker build --build-arg citydb_version=${version} -t tumgis/3dcitydb-postgis:${version} ./${version}
  - docker build --build-arg citydb_version=${version} -t tumgis/3dcitydb-postgis:${version}-alpine ./${version}/alpine

before_script:
  - sleep 30
  - docker run --name ${version} -dit -e "SRID=31468" -e "SRSNAME=EPSG:31468" tumgis/3dcitydb-postgis:${version}
  - docker run --name ${version}-alpine -dit -e "SRID=31468" -e "SRSNAME=EPSG:31468" tumgis/3dcitydb-postgis:${version}-alpine

script:
  - sleep 30
  - docker logs ${version} | grep -Pzl "(?s)Setting up 3DCityDB ... done!.*database system is ready to accept connections"
  - docker logs ${version}-alpine | grep -Pzl "(?s)Setting up 3DCityDB ... done!.*database system is ready to accept connections"
  
notifications:
    slack: tum-gis:Z32lHXJDXaycOn4643NHSXaT
    on_success: change
    on_failure: always
